import { useState } from 'react'
import DataTable from '../../components/panels/DataTable'
import Drawer from '../../components/panels/Drawer'
import { Input, Select, FormSection, FormGrid } from '../../components/controls/FormFields'
import { toast } from '../../components/ui/Toast'
const init=[{id:1,sn:'HW-GPS-001',tipo:'GPS',modelo:'Teltonika FMC130',status:'INSTALADO',tenant:'Mineradora ABC',equip:'CAT-01'},{id:2,sn:'HW-TAB-001',tipo:'Tablet',modelo:'Samsung Tab Active4',status:'INSTALADO',tenant:'Mineradora ABC',equip:'CAT-01'},{id:3,sn:'HW-GPS-002',tipo:'GPS',modelo:'Teltonika FMC130',status:'ESTOQUE',tenant:'—',equip:'—'},{id:4,sn:'HW-GPS-003',tipo:'GPS',modelo:'Teltonika FMC130',status:'MANUTENCAO',tenant:'—',equip:'—'}]
const empty={sn:'',tipo:'GPS',modelo:'',status:'ESTOQUE'}
export default function Hardware(){const [data,setData]=useState(init);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<any>(null);const [form,setForm]=useState<any>(empty);const set=(k:string,v:string)=>setForm((p:any)=>({...p,[k]:v}))
  const save=()=>{if(!form.sn){toast('SN obrigatório','error');return}if(editing){setData(p=>p.map(r=>r.id===editing.id?{...r,...form}:r));toast('Atualizado')}else{setData(p=>[...p,{id:Date.now(),...form,tenant:'—',equip:'—'}]);toast('Hardware registrado')}setOpen(false)}
  const statusColor=(s:string)=>s==='INSTALADO'?'led-ok':s==='ESTOQUE'?'led-off':s==='MANUTENCAO'?'led-warn':'led-crit'
  const columns=[{key:'sn',label:'Serial',render:(r:any)=><span className="text-brand-400 font-bold font-mono">{r.sn}</span>},{key:'tipo',label:'Tipo'},{key:'modelo',label:'Modelo'},{key:'status',label:'Status',render:(r:any)=><div className="flex items-center gap-2"><div className={'led '+statusColor(r.status)}></div><span className="text-[10px]">{r.status}</span></div>},{key:'tenant',label:'Tenant'},{key:'equip',label:'Equipamento'}]
  return (<><DataTable columns={columns} data={data} title="Hardware (Plataforma)" status="neutral" onAdd={()=>{setForm(empty);setEditing(null);setOpen(true)}} onEdit={r=>{setForm({sn:r.sn,tipo:r.tipo,modelo:r.modelo,status:r.status});setEditing(r);setOpen(true)}} addLabel="Novo HW" /><Drawer open={open} onClose={()=>setOpen(false)} title={editing?'Editar':'Novo Hardware'} footer={<><button onClick={()=>setOpen(false)} className="px-4 py-2 text-xs font-mono uppercase text-dim border border-hud-border rounded-md">Cancelar</button><button onClick={save} className="px-4 py-2 text-xs font-mono uppercase text-brand-400 bg-brand-600/20 border border-brand-600/40 rounded-md hover:shadow-glow-sm transition-all">Salvar</button></>}><div className="space-y-6"><FormSection title="Identificação"><Input label="Serial Number" value={form.sn} onChange={v=>set('sn',v)} required /><FormGrid><Select label="Tipo" value={form.tipo} onChange={v=>set('tipo',v)} options={[{value:'GPS',label:'GPS'},{value:'Tablet',label:'Tablet'},{value:'Sensor',label:'Sensor'},{value:'Camera',label:'Câmera'}]} /><Input label="Modelo" value={form.modelo} onChange={v=>set('modelo',v)} /></FormGrid><Select label="Status" value={form.status} onChange={v=>set('status',v)} options={[{value:'ESTOQUE',label:'Estoque'},{value:'INSTALADO',label:'Instalado'},{value:'MANUTENCAO',label:'Manutenção'},{value:'DESCARTADO',label:'Descartado'}]} /></FormSection></div></Drawer></>)}