import { useState } from 'react'
import Panel from '../../components/panels/Panel'
import { toast } from '../../components/ui/Toast'
const funcionalidades = ['Equipamentos','Operadores','Atividades','Abastecimento','Manutenção','Checklist','Áreas','Relatórios','Qualidade','Admin']
const acoes = ['VER','CRIAR','EDITAR','DELETAR','EXPORTAR']
const perfis = ['Administrador','Supervisor','Operador Sala','Visualizador']
export default function Perfis(){const [selected,setSelected]=useState('Administrador');const [perms,setPerms]=useState<Record<string,string[]>>(Object.fromEntries(funcionalidades.map(f=>[f,selected==='Administrador'?[...acoes]:selected==='Supervisor'?['VER','CRIAR','EDITAR','EXPORTAR']:['VER','EXPORTAR']])))
  const toggle=(func:string,acao:string)=>{setPerms(p=>{const cur=p[func]||[];return {...p,[func]:cur.includes(acao)?cur.filter(a=>a!==acao):[...cur,acao]}})}
  const save=()=>toast('Permissões salvas')
  return (<Panel title="Perfis & Permissões" status="neutral" subtitle="MATRIX DE ACESSO" noPad><div className="p-4"><div className="flex items-center gap-2 mb-4">{perfis.map(p=><button key={p} onClick={()=>setSelected(p)} className={'px-3 py-1.5 rounded-md text-xs font-mono transition-all '+(selected===p?'bg-brand-600/20 text-brand-400 border border-brand-600/40':'text-dim border border-hud-border hover:text-gray-300')}>{p}</button>)}<div className="flex-1"/><button onClick={save} className="px-3 py-1.5 text-[10px] font-mono uppercase text-brand-400 bg-brand-600/20 border border-brand-600/40 rounded-md hover:shadow-glow-sm transition-all">Salvar</button></div>
    <div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-hud-border/50"><th className="px-3 py-2 text-left text-[10px] font-mono uppercase text-dim">Funcionalidade</th>{acoes.map(a=><th key={a} className="px-3 py-2 text-center text-[10px] font-mono uppercase text-dim w-20">{a}</th>)}</tr></thead><tbody className="divide-y divide-hud-border/20">{funcionalidades.map(f=><tr key={f} className="hover:bg-white/[0.01]"><td className="px-3 py-2.5 text-xs text-gray-300">{f}</td>{acoes.map(a=><td key={a} className="px-3 py-2.5 text-center"><button onClick={()=>toggle(f,a)} className={'w-5 h-5 rounded border transition-all '+(perms[f]?.includes(a)?'bg-brand-600/30 border-brand-600/50 shadow-glow-sm':'border-hud-border hover:border-gray-600')}>{perms[f]?.includes(a)&&<span className="text-brand-400 text-[10px]">✓</span>}</button></td>)}</tr>)}</tbody></table></div></div></Panel>)}