import { createContext, useContext, useState } from 'react'

export type Locale = 'pt-BR' | 'en' | 'es' | 'de' | 'fr'

const dict: Record<Locale, Record<string, string>> = {
  'pt-BR': { dashboard:'Painel', map:'Mapa', fleet:'Frota', equipment:'Equipamentos', models:'Modelos', groups:'Grupos', manufacturers:'Fabricantes', contractors:'Contratadas', operators:'Operadores', operation:'Operação', activities:'Atividades', cycles:'Ciclos', dispatch:'Dispatch', alerts:'Alertas', shifts:'Turnos', shift_regime:'Regimes de Turno', alert_rules:'Regras de Alerta', fueling:'Abastecimento', records:'Registros', stations:'Postos', fuels:'Combustíveis', messaging:'Mensageria', chat:'Chat', templates:'Templates', checklist:'Checklist', executions:'Execuções', maintenance:'Manutenção', work_orders:'Ordens de Serviço', preventive:'Preventiva', parts:'Peças & Estoque', quality:'Qualidade', areas_routes:'Áreas & Rotas', areas:'Áreas', subareas:'Subáreas', materials:'Materiais', routes:'Rotas', access_points:'Pontos de Acesso', planning:'Planejamento', appropriation:'Apropriação', cost_center:'Centro de Custo', period_closing:'Fechamento', reports:'Relatórios', admin:'Admin', users:'Usuários', profiles:'Perfis & Permissões', hardware:'Hardware', audit:'Auditoria', settings:'Configurações', save:'Salvar', cancel:'Cancelar', delete:'Excluir', create:'Criar', edit:'Editar', search:'Filtrar...', new:'Novo', confirm_delete:'Confirmar exclusão', no_records:'Nenhum registro encontrado', required:'Obrigatório', success_created:'Criado com sucesso', success_updated:'Atualizado com sucesso', success_deleted:'Removido com sucesso', my_profile:'Minha Conta', language:'Idioma', light_mode:'Modo Claro', dark_mode:'Modo Escuro' },
  'en': { dashboard:'Dashboard', map:'Map', fleet:'Fleet', equipment:'Equipment', models:'Models', groups:'Groups', manufacturers:'Manufacturers', contractors:'Contractors', operators:'Operators', operation:'Operation', activities:'Activities', cycles:'Cycles', dispatch:'Dispatch', alerts:'Alerts', shifts:'Shifts', shift_regime:'Shift Regime', alert_rules:'Alert Rules', fueling:'Fueling', records:'Records', stations:'Stations', fuels:'Fuels', messaging:'Messaging', chat:'Chat', templates:'Templates', checklist:'Checklist', executions:'Executions', maintenance:'Maintenance', work_orders:'Work Orders', preventive:'Preventive', parts:'Parts & Stock', quality:'Quality', areas_routes:'Areas & Routes', areas:'Areas', subareas:'Sub-Areas', materials:'Materials', routes:'Routes', access_points:'Access Points', planning:'Planning', appropriation:'Appropriation', cost_center:'Cost Center', period_closing:'Period Closing', reports:'Reports', admin:'Admin', users:'Users', profiles:'Profiles & Permissions', hardware:'Hardware', audit:'Audit', settings:'Settings', save:'Save', cancel:'Cancel', delete:'Delete', create:'Create', edit:'Edit', search:'Filter...', new:'New', confirm_delete:'Confirm deletion', no_records:'No records found', required:'Required', success_created:'Created successfully', success_updated:'Updated successfully', success_deleted:'Deleted successfully', my_profile:'My Account', language:'Language', light_mode:'Light Mode', dark_mode:'Dark Mode' },
  'es': { dashboard:'Panel', map:'Mapa', fleet:'Flota', equipment:'Equipos', models:'Modelos', groups:'Grupos', manufacturers:'Fabricantes', contractors:'Contratistas', operators:'Operadores', operation:'Operación', activities:'Actividades', cycles:'Ciclos', dispatch:'Despacho', alerts:'Alertas', shifts:'Turnos', shift_regime:'Régimen de Turno', alert_rules:'Reglas de Alerta', fueling:'Abastecimiento', records:'Registros', stations:'Estaciones', fuels:'Combustibles', messaging:'Mensajería', chat:'Chat', templates:'Plantillas', checklist:'Checklist', executions:'Ejecuciones', maintenance:'Mantenimiento', work_orders:'Órdenes de Servicio', preventive:'Preventivo', parts:'Piezas & Stock', quality:'Calidad', areas_routes:'Áreas & Rutas', areas:'Áreas', subareas:'Subáreas', materials:'Materiales', routes:'Rutas', access_points:'Puntos de Acceso', planning:'Planificación', appropriation:'Apropiación', cost_center:'Centro de Costo', period_closing:'Cierre de Período', reports:'Reportes', admin:'Admin', users:'Usuarios', profiles:'Perfiles & Permisos', hardware:'Hardware', audit:'Auditoría', settings:'Configuración', save:'Guardar', cancel:'Cancelar', delete:'Eliminar', create:'Crear', edit:'Editar', search:'Filtrar...', new:'Nuevo', confirm_delete:'Confirmar eliminación', no_records:'No se encontraron registros', required:'Obligatorio', success_created:'Creado exitosamente', success_updated:'Actualizado exitosamente', success_deleted:'Eliminado exitosamente', my_profile:'Mi Cuenta', language:'Idioma', light_mode:'Modo Claro', dark_mode:'Modo Oscuro' },
  'de': { dashboard:'Dashboard', map:'Karte', fleet:'Flotte', equipment:'Ausrüstung', models:'Modelle', groups:'Gruppen', manufacturers:'Hersteller', contractors:'Auftragnehmer', operators:'Bediener', operation:'Betrieb', activities:'Aktivitäten', cycles:'Zyklen', dispatch:'Dispatch', alerts:'Warnungen', shifts:'Schichten', shift_regime:'Schichtregime', alert_rules:'Alarmregeln', fueling:'Betankung', records:'Einträge', stations:'Tankstellen', fuels:'Kraftstoffe', messaging:'Nachrichten', chat:'Chat', templates:'Vorlagen', checklist:'Checkliste', executions:'Ausführungen', maintenance:'Wartung', work_orders:'Arbeitsaufträge', preventive:'Präventiv', parts:'Teile & Lager', quality:'Qualität', areas_routes:'Bereiche & Routen', areas:'Bereiche', subareas:'Unterbereiche', materials:'Materialien', routes:'Routen', access_points:'Zugangspunkte', planning:'Planung', appropriation:'Zuordnung', cost_center:'Kostenstelle', period_closing:'Periodenabschluss', reports:'Berichte', admin:'Admin', users:'Benutzer', profiles:'Profile & Berechtigungen', hardware:'Hardware', audit:'Audit', settings:'Einstellungen', save:'Speichern', cancel:'Abbrechen', delete:'Löschen', create:'Erstellen', edit:'Bearbeiten', search:'Filtern...', new:'Neu', confirm_delete:'Löschung bestätigen', no_records:'Keine Einträge gefunden', required:'Pflichtfeld', success_created:'Erfolgreich erstellt', success_updated:'Erfolgreich aktualisiert', success_deleted:'Erfolgreich gelöscht', my_profile:'Mein Konto', language:'Sprache', light_mode:'Hellmodus', dark_mode:'Dunkelmodus' },
  'fr': { dashboard:'Tableau de bord', map:'Carte', fleet:'Flotte', equipment:'Équipements', models:'Modèles', groups:'Groupes', manufacturers:'Fabricants', contractors:'Sous-traitants', operators:'Opérateurs', operation:'Opération', activities:'Activités', cycles:'Cycles', dispatch:'Dispatch', alerts:'Alertes', shifts:'Équipes', shift_regime:'Régime d\'équipe', alert_rules:'Règles d\'alerte', fueling:'Ravitaillement', records:'Registres', stations:'Stations', fuels:'Carburants', messaging:'Messagerie', chat:'Chat', templates:'Modèles', checklist:'Checklist', executions:'Exécutions', maintenance:'Maintenance', work_orders:'Ordres de travail', preventive:'Préventive', parts:'Pièces & Stock', quality:'Qualité', areas_routes:'Zones & Routes', areas:'Zones', subareas:'Sous-zones', materials:'Matériaux', routes:'Routes', access_points:'Points d\'accès', planning:'Planification', appropriation:'Appropriation', cost_center:'Centre de coût', period_closing:'Clôture', reports:'Rapports', admin:'Admin', users:'Utilisateurs', profiles:'Profils & Permissions', hardware:'Matériel', audit:'Audit', settings:'Paramètres', save:'Enregistrer', cancel:'Annuler', delete:'Supprimer', create:'Créer', edit:'Modifier', search:'Filtrer...', new:'Nouveau', confirm_delete:'Confirmer la suppression', no_records:'Aucun enregistrement trouvé', required:'Obligatoire', success_created:'Créé avec succès', success_updated:'Mis à jour avec succès', success_deleted:'Supprimé avec succès', my_profile:'Mon Compte', language:'Langue', light_mode:'Mode Clair', dark_mode:'Mode Sombre' },
}

const localeNames: Record<Locale, string> = { 'pt-BR':'Português', 'en':'English', 'es':'Español', 'de':'Deutsch', 'fr':'Français' }

interface I18nCtx { locale: Locale; setLocale: (l: Locale) => void; t: (key: string) => string; localeNames: Record<Locale, string> }
const Ctx = createContext<I18nCtx>({ locale: 'pt-BR', setLocale: () => {}, t: (k) => k, localeNames })

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => (localStorage.getItem('sl-locale') as Locale) || 'pt-BR')
  const t = (key: string) => dict[locale]?.[key] || dict['pt-BR']?.[key] || key
  const change = (l: Locale) => { setLocale(l); localStorage.setItem('sl-locale', l) }
  return <Ctx.Provider value={{ locale, setLocale: change, t, localeNames }}>{children}</Ctx.Provider>
}

export const useI18n = () => useContext(Ctx)
