import { useState } from 'react'
import DataTable from '../../components/panels/DataTable'
import Drawer from '../../components/panels/Drawer'
import ConfirmDialog from '../../components/ui/ConfirmDialog'
import { Input, Select, FormSection, FormGrid } from '../../components/controls/FormFields'
import { toast } from '../../components/ui/Toast'
const init = [{id:1,rota:'Frente Norte→Britador',material:'ROM',centro_custo:'CC-001',dmt:2.8,tempo_carga:4.2,tempo_transp:8.5,status:'ATIVA'},{id:2,rota:'Frente Sul→Pilha Estéril',material:'Estéril',centro_custo:'CC-002',dmt:2.1,tempo_carga:3.8,tempo_transp:7.2,status:'ATIVA'},{id:3,rota:'Frente Norte→Pilha ROM',material:'ROM',centro_custo:'CC-001',dmt:1.5,tempo_carga:4.0,tempo_transp:6.2,status:'ATIVA'}]
const empty = {rota:'',material:'',centro_custo:'',dmt:'',tempo_carga:'',tempo_transp:''}
export default function Apropriacao() {
  const [data,setData]=useState(init);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<any>(null);const [del,setDel]=useState<any>(null);const [form,setForm]=useState<any>(empty)
  const set=(k:string,v:string)=>setForm((p:any)=>({...p,[k]:v}))
  const save=()=>{if(!form.rota){toast('Rota obrigatória','error');return}if(editing){setData(p=>p.map(r=>r.id===editing.id?{...r,...form,dmt:+form.dmt,tempo_carga:+form.tempo_carga,tempo_transp:+form.tempo_transp}:r));toast('Atualizado')}else{setData(p=>[...p,{id:Date.now(),...form,dmt:+form.dmt,tempo_carga:+form.tempo_carga,tempo_transp:+form.tempo_transp,status:'ATIVA'}]);toast('Criado')}setOpen(false)}
  const columns=[{key:'rota',label:'Rota',render:(r:any)=><span className="text-brand-400 font-medium">{r.rota}</span>},{key:'material',label:'Material'},{key:'centro_custo',label:'Centro Custo',render:(r:any)=><span className="font-mono">{r.centro_custo}</span>},{key:'dmt',label:'DMT',render:(r:any)=><span className="font-mono">{r.dmt} km</span>},{key:'tempo_carga',label:'T.Carga',render:(r:any)=><span className="font-mono">{r.tempo_carga} min</span>},{key:'tempo_transp',label:'T.Transp',render:(r:any)=><span className="font-mono">{r.tempo_transp} min</span>}]
  return (<><DataTable columns={columns} data={data} title="Apropriação de Rotas" status="info" onAdd={()=>{setForm(empty);setEditing(null);setOpen(true)}} onEdit={r=>{setForm({rota:r.rota,material:r.material,centro_custo:r.centro_custo,dmt:String(r.dmt),tempo_carga:String(r.tempo_carga),tempo_transp:String(r.tempo_transp)});setEditing(r);setOpen(true)}} onDelete={setDel} addLabel="Nova Apropriação" />
    <Drawer open={open} onClose={()=>setOpen(false)} title={editing?'Editar':'Nova Apropriação'} footer={<><button onClick={()=>setOpen(false)} className="px-4 py-2 text-xs font-mono uppercase text-dim border border-hud-border rounded-md">Cancelar</button><button onClick={save} className="px-4 py-2 text-xs font-mono uppercase text-brand-400 bg-brand-600/20 border border-brand-600/40 rounded-md hover:shadow-glow-sm transition-all">Salvar</button></>}><div className="space-y-6"><FormSection title="Rota"><Input label="Rota (Origem→Destino)" value={form.rota} onChange={v=>set('rota',v)} required /><FormGrid><Input label="Material" value={form.material} onChange={v=>set('material',v)} /><Input label="Centro de Custo" value={form.centro_custo} onChange={v=>set('centro_custo',v)} /></FormGrid></FormSection><FormSection title="Tempos"><FormGrid><Input label="DMT (km)" value={form.dmt} onChange={v=>set('dmt',v)} type="number" /><Input label="T. Carga (min)" value={form.tempo_carga} onChange={v=>set('tempo_carga',v)} type="number" /></FormGrid><Input label="T. Transporte (min)" value={form.tempo_transp} onChange={v=>set('tempo_transp',v)} type="number" /></FormSection></div></Drawer>
    <ConfirmDialog open={!!del} onClose={()=>setDel(null)} onConfirm={()=>{setData(p=>p.filter(r=>r.id!==del.id));toast('Removido');setDel(null)}} title="Excluir" message="Confirma?" confirmLabel="Excluir" /></>)
}