import { useState } from 'react'
import { useT } from '../../contexts/LanguageContext'
import DataTable from '../../components/panels/DataTable'
import Drawer from '../../components/panels/Drawer'
import ConfirmDialog from '../../components/ui/ConfirmDialog'
import { Input, FormSection, FormGrid } from '../../components/controls/FormFields'
import { toast } from '../../components/ui/Toast'
const init=[{id:1,codigo:'CC-001',nome:'Lavra Norte'},{id:2,codigo:'CC-002',nome:'Lavra Sul'},{id:3,codigo:'CC-003',nome:'Beneficiamento'},{id:4,codigo:'CC-004',nome:'Infraestrutura'}]
const empty={codigo:'',nome:''}
export default function CentroCusto(){
  const t = useT()
  const [data,setData]=useState(init);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<any>(null);const [del,setDel]=useState<any>(null);const [form,setForm]=useState<any>(empty);const set=(k:string,v:string)=>setForm((p:any)=>({...p,[k]:v}));const save=()=>{if(!form.codigo||!form.nome){toast('Obrigatório','error');return}if(editing){setData(p=>p.map(r=>r.id===editing.id?{...r,...form}:r));toast('Atualizado')}else{setData(p=>[...p,{id:Date.now(),...form}]);toast('Criado')}setOpen(false)}
  const columns=[{key:'codigo',label:'Código',render:(r:any)=><span className="text-brand-400 font-bold font-mono">{r.codigo}</span>},{key:'nome',label:'Nome',render:(r:any)=><span className="text-gray-200">{r.nome}</span>}]
  return (<><DataTable columns={columns} data={data} title="Centros de Custo" status="neutral" onAdd={()=>{setForm(empty);setEditing(null);setOpen(true)}} onEdit={r=>{setForm({codigo:r.codigo,nome:r.nome});setEditing(r);setOpen(true)}} onDelete={setDel} addLabel="Novo CC" /><Drawer open={open} onClose={()=>setOpen(false)} title={editing?'Editar':'Novo Centro de Custo'} footer={<><button onClick={()=>setOpen(false)} className="px-4 py-2 text-xs font-mono uppercase text-dim border border-hud-border rounded-md">Cancelar</button><button onClick={save} className="px-4 py-2 text-xs font-mono uppercase text-brand-400 bg-brand-600/20 border border-brand-600/40 rounded-md hover:shadow-glow-sm transition-all">Salvar</button></>}><div className="space-y-6"><FormSection title="Dados"><FormGrid><Input label="Código" value={form.codigo} onChange={v=>set('codigo',v)} required placeholder="CC-001" /><Input label="Nome" value={form.nome} onChange={v=>set('nome',v)} required /></FormGrid></FormSection></div></Drawer><ConfirmDialog open={!!del} onClose={()=>setDel(null)} onConfirm={()=>{setData(p=>p.filter(r=>r.id!==del.id));toast('Removido');setDel(null)}} title="Excluir" message="Confirma?" confirmLabel="Excluir" /></>)}