import { useState } from 'react'
import Panel from '../../components/panels/Panel'
import Drawer from '../../components/panels/Drawer'
import { Input, Textarea, FormSection } from '../../components/controls/FormFields'
import { toast } from '../../components/ui/Toast'
import { Lock, Unlock, RotateCcw } from 'lucide-react'
const init=[{id:1,periodo:'2024-06',nome:'Junho 2024',status:'ABERTO',dt_fechamento:null,justificativa:null},{id:2,periodo:'2024-05',nome:'Maio 2024',status:'FECHADO',dt_fechamento:'2024-06-05',justificativa:null},{id:3,periodo:'2024-04',nome:'Abril 2024',status:'FECHADO',dt_fechamento:'2024-05-03',justificativa:null}]
export default function Fechamento(){const [data,setData]=useState(init);const [reopen,setReopen]=useState<any>(null);const [justificativa,setJustificativa]=useState('')
  const fechar=(id:number)=>{setData(p=>p.map(r=>r.id===id?{...r,status:'FECHADO',dt_fechamento:new Date().toISOString().slice(0,10)}:r));toast('Período fechado')}
  const reabrir=()=>{if(!justificativa){toast('Justificativa obrigatória','error');return}setData(p=>p.map(r=>r.id===reopen.id?{...r,status:'REABERTO',justificativa}:r));toast('Período reaberto');setReopen(null);setJustificativa('')}
  return (<div className="space-y-4"><Panel title="Fechamento de Período" status="info" subtitle="CONTROLE MENSAL" noPad><div className="divide-y divide-hud-border/30">{data.map(p=>(<div key={p.id} className="flex items-center justify-between px-5 py-4"><div className="flex items-center gap-3"><div className={'led led-'+(p.status==='ABERTO'?'ok':p.status==='FECHADO'?'off':'warn')}></div><div><span className="text-sm font-mono text-gray-200">{p.nome}</span><span className="text-[10px] text-dim ml-3">{p.periodo}</span></div></div><div className="flex items-center gap-3">{p.status==='FECHADO'&&<span className="text-[10px] font-mono text-dim">Fechado em {p.dt_fechamento}</span>}<span className={'px-2 py-0.5 rounded text-[10px] border font-mono '+(p.status==='ABERTO'?'text-ok bg-ok/10 border-ok/20':p.status==='FECHADO'?'text-dim bg-white/5 border-hud-border':'text-warn bg-warn/10 border-warn/20')}>{p.status}</span>{p.status==='ABERTO'&&<button onClick={()=>fechar(p.id)} className="flex items-center gap-1 px-3 py-1.5 text-[10px] font-mono uppercase text-brand-400 bg-brand-600/10 border border-brand-600/30 rounded-md hover:shadow-glow-sm transition-all"><Lock className="w-3 h-3"/>Fechar</button>}{p.status==='FECHADO'&&<button onClick={()=>setReopen(p)} className="flex items-center gap-1 px-3 py-1.5 text-[10px] font-mono uppercase text-warn bg-warn/10 border border-warn/30 rounded-md hover:shadow-glow-warn transition-all"><RotateCcw className="w-3 h-3"/>Reabrir</button>}</div></div>))}</div></Panel>
    <Drawer open={!!reopen} onClose={()=>setReopen(null)} title="Reabrir Período" subtitle={reopen?.nome} footer={<><button onClick={()=>setReopen(null)} className="px-4 py-2 text-xs font-mono uppercase text-dim border border-hud-border rounded-md">Cancelar</button><button onClick={reabrir} className="px-4 py-2 text-xs font-mono uppercase text-warn bg-warn/10 border border-warn/30 rounded-md hover:shadow-glow-warn transition-all">Confirmar Reabertura</button></>}><div className="space-y-6"><FormSection title="Justificativa (obrigatória)"><Textarea label="Motivo da reabertura" value={justificativa} onChange={setJustificativa} placeholder="Descreva o motivo..." rows={4} /></FormSection><div className="p-3 bg-warn/5 border border-warn/20 rounded-lg"><p className="text-xs text-warn">⚠ Reabrir um período fechado permite edição de dados históricos. Esta ação será registrada na auditoria.</p></div></div></Drawer></div>)}