import { useState } from 'react'
import { useT } from '../../contexts/LanguageContext'
import DataTable from '../../components/panels/DataTable'
import Drawer from '../../components/panels/Drawer'
import ConfirmDialog from '../../components/ui/ConfirmDialog'
import { Input, Select, FormSection, FormGrid, Toggle } from '../../components/controls/FormFields'
import { toast } from '../../components/ui/Toast'
import { Play, Calendar } from 'lucide-react'
const init=[{id:1,nome:'Produção Diária',tipo:'OPERACIONAL',formato:'PDF',agendado:true,cron:'Diário 06:00',ultimo:'09/06 06:00'},{id:2,nome:'DF% Semanal',tipo:'KPI',formato:'EXCEL',agendado:true,cron:'Segunda 08:00',ultimo:'03/06 08:00'},{id:3,nome:'Consumo Combustível',tipo:'CUSTOS',formato:'PDF',agendado:false,cron:'',ultimo:'05/06 14:30'},{id:4,nome:'Manutenção Pendente',tipo:'MANUTENCAO',formato:'PDF',agendado:false,cron:'',ultimo:'08/06 10:00'}]
const empty={nome:'',tipo:'OPERACIONAL',formato:'PDF',agendado:false}
export default function Relatorios(){
  const t = useT()
  const [data,setData]=useState(init);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<any>(null);const [del,setDel]=useState<any>(null);const [form,setForm]=useState<any>(empty);const set=(k:string,v:any)=>setForm((p:any)=>({...p,[k]:v}))
  const save=()=>{if(!form.nome){toast('Nome obrigatório','error');return}if(editing){setData(p=>p.map(r=>r.id===editing.id?{...r,...form}:r));toast('Atualizado')}else{setData(p=>[...p,{id:Date.now(),...form,cron:'',ultimo:'—'}]);toast('Relatório criado')}setOpen(false)}
  const executar=(id:number)=>{setData(p=>p.map(r=>r.id===id?{...r,ultimo:new Date().toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}:r));toast('Relatório executado')}
  const columns=[{key:'nome',label:'Nome',render:(r:any)=><span className="text-gray-200 font-medium">{r.nome}</span>},{key:'tipo',label:'Tipo',render:(r:any)=><span className="px-2 py-0.5 bg-brand-600/10 border border-brand-600/20 rounded text-[10px] text-brand-400">{r.tipo}</span>},{key:'formato',label:'Formato',render:(r:any)=><span className="font-mono text-[10px]">{r.formato}</span>},{key:'agendado',label:'Agendado',render:(r:any)=>r.agendado?<span className="flex items-center gap-1 text-ok text-[10px]"><Calendar className="w-3 h-3"/>{r.cron}</span>:<span className="text-dim text-[10px]">Manual</span>},{key:'ultimo',label:'Última Exec.'},{key:'exec',label:'',render:(r:any)=><button onClick={()=>executar(r.id)} className="flex items-center gap-1 px-2 py-1 text-[9px] font-mono uppercase text-brand-400 bg-brand-600/10 border border-brand-600/30 rounded hover:shadow-glow-sm transition-all"><Play className="w-3 h-3"/>Executar</button>,sortable:false}]
  return (<><DataTable columns={columns} data={data} title={t.reports.title} status="neutral" onAdd={()=>{setForm(empty);setEditing(null);setOpen(true)}} onEdit={r=>{setForm({nome:r.nome,tipo:r.tipo,formato:r.formato,agendado:r.agendado});setEditing(r);setOpen(true)}} onDelete={setDel} addLabel="Novo Relatório" /><Drawer open={open} onClose={()=>setOpen(false)} title={editing?'Editar':'Novo Relatório'} footer={<><button onClick={()=>setOpen(false)} className="px-4 py-2 text-xs font-mono uppercase text-dim border border-hud-border rounded-md">Cancelar</button><button onClick={save} className="px-4 py-2 text-xs font-mono uppercase text-brand-400 bg-brand-600/20 border border-brand-600/40 rounded-md hover:shadow-glow-sm transition-all">Salvar</button></>}><div className="space-y-6"><FormSection title="Dados"><Input label="Nome" value={form.nome} onChange={v=>set('nome',v)} required /><FormGrid><Select label="Tipo" value={form.tipo} onChange={v=>set('tipo',v)} options={[{value:'OPERACIONAL',label:'Operacional'},{value:'KPI',label:'KPI'},{value:'CUSTOS',label:'Custos'},{value:'MANUTENCAO',label:'Manutenção'}]} /><Select label="Formato" value={form.formato} onChange={v=>set('formato',v)} options={[{value:'PDF',label:'PDF'},{value:'EXCEL',label:'Excel'},{value:'CSV',label:'CSV'}]} /></FormGrid></FormSection><FormSection title="Agendamento"><Toggle label="Agendar execução automática" checked={form.agendado} onChange={v=>set('agendado',v)} /></FormSection></div></Drawer><ConfirmDialog open={!!del} onClose={()=>setDel(null)} onConfirm={()=>{setData(p=>p.filter(r=>r.id!==del.id));toast('Removido');setDel(null)}} title="Excluir" message="Confirma?" confirmLabel="Excluir" /></>)}